set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -s escape-time 0
set -g history-limit 100000
set -g mouse on
set -g set-clipboard on
set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1
setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

if-shell "[ -f \"$HOME/.config/dev-environment/private/dotfiles/shared/tmux/tmux.conf\" ]" "source-file \"$HOME/.config/dev-environment/private/dotfiles/shared/tmux/tmux.conf\""
